version: '3'
services:
    frontend:
        build: images/apache
        image: onyx/frontend
        volumes:
            - ..:/var/www/onyx
            - ../system/bash-history/.frontend:/root/.bash_history
        ports:
            - "${WEB_PORT}:80"
        links:
            - rabbitmq
        environment:
            - USER_ID=${USER_ID}
            - GROUP_ID=${GROUP_ID}
            - PHP_XDEBUG_ENABLED=1
    rabbitmq:
        image: rabbitmq:3-management-alpine
        hostname: rabbitmq
        ports:
            - "${RMQ_PORT}:15672"
            - "5672:5672"
